### ISSUE TITLE
Refactor OpenFile to use FileLocation

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava-plugins-commands#1]
Currently `OpenFile` uses [file.getAbsolutePath](https://github.com/scijava/scijava-plugins-commands/blob/c1fbbd44a240213b748ef005afc478b9bbbf291d/src/main/java/org/scijava/plugins/commands/io/OpenFile.java#L83-L84) and passes the string result to the `IOService`. 

Instead we should be wrapping the `File` in a [Location](https://github.com/scijava/scijava-common/blob/master/src/main/java/org/scijava/io/location/FileLocation.java) and passing that.

**Comment by hinerm** [comment]
Success for this issue is that [ExecuteCommands](https://github.com/imagej/tutorials/blob/master/java/execute-commands/src/main/java/ExecuteCommands.java) works with the latest pom-scijava (and development version of `scijava-plugins-commands`, if not other libraries as well).

However, I suspect this change as-written will not be sufficient as the SCIFIO [TestImgFormat](https://github.com/scifio/scifio/blob/9d9e56e46d747d9a7b9ad78000057f512bfb15e0/src/main/java/io/scif/formats/TestImgFormat.java#L371) only operates on `TestImgLocation`s.

So we will probably also want to create an `OpenLocation` command that takes a `Location` instead of a `File` and then update `ExecuteCommands` to just create and pass it a `TestImgLocation`.

**Comment by ctrueden** [comment]
@hinerm I do not think the issue with `ExecuteCommands` is relevant to this issue here. The problem there is with changes to SCIFIO's `.fake` file logic. The fix will not happen in this repository.

**Comment by hinerm** [comment]
@ctrueden This issue is for `ecmagnusson`, who I want to test the `ExecuteCommands` with a dev version of this repo. It may result in new commands in this repo as I mentioned above.

**Comment by ctrueden** [comment]
I also think creating an `OpenLocation` command is not useful, because `Location` parameters cannot be harvested by the input harvester, and so this command appearing in the menus is not usable for users.

**Comment by ctrueden** [comment]
OK, well I leave it to you then, but I think my fix was the correct one with respect to the issue described above.

**Comment by hinerm** [comment]
Closing in favor of https://github.com/imagej/tutorials/issues/101
